#!/bin/bash

set -e
if [[ -d exec.d ]]; then
    shopt -s nullglob
    for f in exec.d/*/charm-pre-install; do 
        [[ -x "$f" ]] || continue
        ${SHELL} -c "$f"|| {
            ## bail out if anyone fails
            juju-log -l ERROR "$f: returned exit_status=$? "
            exit 1
        }
    done
fi

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq memcached

cat > /etc/default/memcached <<EOF
ENABLE_MEMCACHED=yes
EOF
